#pragma once

#include "cocos2d.h"
#include "GameObject.h"
#include "GameDefs.h"
#include <string>

/**
 * @brief Coin class for collecting sun points
 * Can be generated by Sunflowers or dropped from sky
 */
class Coin : public GameObject
{
public:

    static enum CoinType{
        SILVER,
        GOLD,
        DIAMOND
    };
    /**
     * @brief Initialization function
     */
    bool init(CoinType CoinType);

    static Coin* create(CoinType coinType);

    /**
     * @brief Update function for movement and lifetime
     * @param delta Time delta
     */
    virtual void update(float delta) override;

    /**
     * @brief Check if sun is collectible
     * @return true if collectible, false otherwise
     */
    bool isCollectible() const;

    /**
     * @brief Collect the sun (returns sun value and marks for removal)
     * @return Coin value (usually 25)
     */
    void collect(const std::function<void(int)>& onfinished);

    /**
     * @brief Check if sun should be removed (expired or collected)
     * @return true if should be removed
     */
    bool shouldRemove() const;

protected:
    Coin();
    virtual ~Coin();

    /**
     * @brief Set up animation (placeholder for now)
     */
    void setAnimation();

    // ----------------------------------------------------
    // Static constants
    // ----------------------------------------------------
    static const std::string IMAGE_FILENAME[3];
    static const int COIN_VALUE[3];           // Coin points awarded
    static const float LIFETIME;          // Lifetime before auto-disappear (10 seconds)

    // ----------------------------------------------------
    // Member variables
    // ----------------------------------------------------
    bool _isCollected;        // Has been collected
    bool _isCollecting;
    float _lifeTime;          // Time elapsed since creation
    cocos2d::Vec2 _targetPos; // Target position for falling suns
    float _coinScale;          // Scale factor for sun size
    CoinType _coinType;            // Coin points awarded (customizable)
};
