#pragma once

#include "cocos2d.h"
#include "GameObject.h"
#include "GameDefs.h"

/**
 * @brief Sun class for collecting sun points
 * Can be generated by Sunflowers or dropped from sky
 */
class Sun : public GameObject
{
public:
    /**
     * @brief Initialization function
     */
    virtual bool init() override;

    CREATE_FUNC(Sun);

    /**
     * @brief Create a sun produced by sunflower at plant position
     * @param pos Sunflower position
     * @return Sun instance
     */
    static Sun* createFromSunflower(const cocos2d::Vec2& pos);

    /**
     * @brief Create a custom sun with specific size and value at plant position
     * @param pos Plant position
     * @param scale Scale factor for sun size
     * @param value Sun value (points awarded)
     * @return Sun instance
     */
    static Sun* createCustomSun(const cocos2d::Vec2& pos, float scale, int value);

    /**
     * @brief Create a sun dropped from sky
     * @param targetGridCol Target grid column to fall to
     * @param startY Starting Y position (top of screen)
     * @return Sun instance
     */
    static Sun* createFromSky(int targetGridCol, float startY);

    /**
     * @brief Update function for movement and lifetime
     * @param delta Time delta
     */
    virtual void update(float delta) override;

    /**
     * @brief Check if sun is collectible
     * @return true if collectible, false otherwise
     */
    bool isCollectible() const;

    /**
     * @brief Collect the sun (returns sun value and marks for removal)
     * @return Sun value (usually 25)
     */
    int collect();

    /**
     * @brief Check if sun should be removed (expired or collected)
     * @return true if should be removed
     */
    bool shouldRemove() const;

protected:
    Sun();
    virtual ~Sun();

    /**
     * @brief Set up animation (placeholder for now)
     */
    void setAnimation();

    // ----------------------------------------------------
    // Static constants
    // ----------------------------------------------------
    static const std::string IMAGE_FILENAME;
    static const int SUN_VALUE;           // Sun points awarded
    static const float FALL_SPEED;        // Fall speed for sky suns
    static const float LIFETIME;          // Lifetime before auto-disappear (10 seconds)

    // ----------------------------------------------------
    // Member variables
    // ----------------------------------------------------
    bool _isCollected;        // Has been collected
    bool _isFalling;          // Is falling from sky
    float _lifeTime;          // Time elapsed since creation
    cocos2d::Vec2 _targetPos; // Target position for falling suns
    float _sunScale;          // Scale factor for sun size
    int _sunValue;            // Sun points awarded (customizable)
};
